platform :android do
  desc "Upload AAB to Open testing track"
  lane :upload_to_open do
    supply(
      json_key_data: ENV["GOOGLE_PLAY_JSON_KEY"],
      package_name: "com.quizbridge.app",
      aab: "build_output/com.quizbridge.app_3.1.aab",
      track: "beta", # ← вот так!
      release_status: "completed",
      skip_upload_changelogs: false,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_metadata: true
    )
  end
end
