platform :android do
  desc "Upload AAB to Internal track"
  lane :upload_to_internal do
    supply(
      json_key_data: ENV["GOOGLE_PLAY_JSON_KEY"],
      package_name: "com.quizbridge.app",
      aab: Dir["build_output/*.aab"].first,
      track: "internal",
      release_status: "draft",
      skip_upload_changelogs: false,
      skip_upload_images: true,
      skip_upload_screenshots: true,
      skip_upload_metadata: true
    )
  end
end
